# Generated by Django 6.0.6 on 2026-06-14 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('2fa', 'Two-Factor Authentication'), ('password_reset', 'Password Reset'), ('email_verify', 'Email Verification')], default='2fa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LLMQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('market_analysis', 'Market Analysis'), ('trading_idea', 'Trading Idea'), ('rag_query', 'Knowledge Query'), ('sentiment', 'Sentiment Analysis')], max_length=30)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True, default='')),
                ('context_used', models.JSONField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAGChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=12)),
                ('text', models.TextField()),
                ('start_pos', models.IntegerField(default=0)),
                ('end_pos', models.IntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Manual Upload'), ('web', 'Web Scrape'), ('api', 'API Import'), ('email', 'Email Import')], default='manual', max_length=50)),
                ('file_type', models.CharField(blank=True, default='', max_length=20)),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('chunk_count', models.IntegerField(default=0)),
                ('is_indexed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro')], default='FREE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=14)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop')], default='MARKET', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_live', models.BooleanField(default=False)),
                ('broker_trade_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=10)),
                ('confidence', models.IntegerField(default=0, help_text='Confidence percentage 0-100')),
                ('entry_price', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(choices=[('AI', 'AI Analysis'), ('MANUAL', 'Manual'), ('SYSTEM', 'System')], default='AI', max_length=50)),
                ('is_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='broker_account_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='broker_api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='broker_api_secret',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_trades_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_trade_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='trading_app_email_282caf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['two_factor_enabled'], name='trading_app_two_fac_8abd50_idx'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ragdocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ragchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='trading_app.ragdocument'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='trading_app_user_id_fe2b80_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['expires_at'], name='trading_app_expires_0b587e_idx'),
        ),
        migrations.AddIndex(
            model_name='llmquery',
            index=models.Index(fields=['user', 'query_type'], name='trading_app_user_id_03bdb9_idx'),
        ),
        migrations.AddIndex(
            model_name='llmquery',
            index=models.Index(fields=['created_at'], name='trading_app_created_7e7c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='ragdocument',
            index=models.Index(fields=['user'], name='trading_app_user_id_c03fac_idx'),
        ),
        migrations.AddIndex(
            model_name='ragdocument',
            index=models.Index(fields=['source'], name='trading_app_source_da8021_idx'),
        ),
        migrations.AddIndex(
            model_name='ragdocument',
            index=models.Index(fields=['is_indexed'], name='trading_app_is_inde_e46826_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchunk',
            index=models.Index(fields=['document'], name='trading_app_documen_c897ec_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchunk',
            index=models.Index(fields=['chunk_id'], name='trading_app_chunk_i_0c2f75_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'status'], name='trading_app_user_id_5787e1_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol'], name='trading_app_symbol_52aef2_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['created_at'], name='trading_app_created_878660_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['user', 'signal_type'], name='trading_app_user_id_b5506f_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['symbol', 'created_at'], name='trading_app_symbol_ae5170_idx'),
        ),
    ]
