# Generated by Django 6.0.6 on 2026-06-14 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0002_emailotp_llmquery_ragchunk_ragdocument_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('school', 'What was the name of your elementary school?'), ('city', 'In which city were you born?'), ('mother', "What is your mother's maiden name?"), ('book', 'What was your favorite book as a child?'), ('movie', 'What was your favorite movie as a teenager?'), ('car', 'What was the make of your first car?'), ('teacher', 'What was the name of your favorite teacher?')], max_length=20)),
                ('answer_hash', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='trading_app_user_id_3e7994_idx')],
                'unique_together': {('user', 'question_key')},
            },
        ),
    ]
