# Generated by Django 6.0.6 on 2026-06-20 05:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paper_mode',
            field=models.BooleanField(default=True, help_text='Paper/demo mode — no real broker execution'),
        ),
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_per_trade', models.DecimalField(decimal_places=1, default=Decimal('2.0'), help_text='Max risk per trade as % of balance', max_digits=4)),
                ('max_daily_trades', models.IntegerField(default=5, help_text='Max trades per day')),
                ('max_drawdown', models.DecimalField(decimal_places=1, default=Decimal('10.0'), help_text='Max drawdown % before trading is halted', max_digits=4)),
                ('daily_profit_target', models.DecimalField(decimal_places=1, default=Decimal('5.0'), help_text='Daily profit target %', max_digits=4)),
                ('max_position_size', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Max volume per position (lots)', max_digits=10)),
                ('auto_execute', models.BooleanField(default=False, help_text='Auto-execute signals without manual confirmation')),
                ('trading_enabled', models.BooleanField(default=True, help_text='Master toggle for all trading')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Configuration',
            },
        ),
    ]
