# Generated by Django 6.0.6 on 2026-06-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0007_user_paper_mode_riskconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Current market price for paper trades', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='unrealized_pnl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unrealized P&L for open paper trades', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.JSONField(blank=True, default=list, help_text='User-preferred trading symbols'),
        ),
    ]
