# Generated by Django 6.0.6 on 2026-07-14 09:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0008_trade_current_price_trade_unrealized_pnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskconfig',
            name='max_exposure_percent',
            field=models.DecimalField(decimal_places=1, default=Decimal('20.0'), help_text='Max total exposure as % of balance', max_digits=5),
        ),
        migrations.AddField(
            model_name='riskconfig',
            name='max_open_positions',
            field=models.IntegerField(default=5, help_text='Max simultaneous open positions'),
        ),
        migrations.AddField(
            model_name='riskconfig',
            name='min_confidence',
            field=models.IntegerField(default=60, help_text='Minimum signal confidence % to auto-execute'),
        ),
        migrations.AddField(
            model_name='riskconfig',
            name='trailing_stop_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Trailing stop % (blank to disable)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
