# Generated by Django 6.0.6 on 2026-07-22 12:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0009_riskconfig_max_exposure_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stake_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Stake amount per trade in account currency', max_digits=12),
        ),
    ]
