# Generated by Django 6.0.6 on 2026-07-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0010_add_stake_amount'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='llmquery',
            name='trading_app_user_id_03bdb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='llmquery',
            name='trading_app_created_7e7c9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragchunk',
            name='trading_app_documen_c897ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragchunk',
            name='trading_app_chunk_i_0c2f75_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragdocument',
            name='trading_app_user_id_c03fac_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragdocument',
            name='trading_app_source_da8021_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragdocument',
            name='trading_app_is_inde_e46826_idx',
        ),
        migrations.RemoveField(
            model_name='ragchunk',
            name='document',
        ),
        migrations.RemoveField(
            model_name='ragdocument',
            name='user',
        ),
        migrations.DeleteModel(
            name='LLMQuery',
        ),
        migrations.DeleteModel(
            name='RAGChunk',
        ),
        migrations.DeleteModel(
            name='RAGDocument',
        ),
    ]
