<<<<<<< HEAD
# Generated by Django 6.0.6 on 2026-07-29 06:31
=======
# Generated by Django 6.0.6 on 2026-07-29 06:55
>>>>>>> 81829296490c85065d16b8cbf6f07965400a1088

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0011_remove_llmquery_trading_app_user_id_03bdb9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskconfig',
            name='auto_execute',
            field=models.BooleanField(default=True, help_text='Auto-execute signals without manual confirmation'),
        ),
    ]
