# Generated by Django 6.0.6 on 2026-08-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0012_alter_riskconfig_auto_execute'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('granularity', models.IntegerField(default=900)),
                ('horizon', models.IntegerField(default=4)),
                ('bias', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('probability', models.FloatField(default=0.5)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('candle_time', models.BigIntegerField(default=0, help_text='Epoch of the entry candle close')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('realized_target', models.IntegerField(blank=True, help_text='1 = price rose over horizon, 0 = fell', null=True)),
                ('prediction_correct', models.BooleanField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'resolved'], name='trading_app_symbol_8c6146_idx'), models.Index(fields=['predicted_at'], name='trading_app_predict_bf0dbc_idx')],
            },
        ),
    ]
