# Generated by Django 6.0.6 on 2026-08-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0013_predictionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_market',
            field=models.CharField(blank=True, default='EUR/USD', help_text='The market currently selected in the bot panel — the bot only trades this symbol', max_length=30),
        ),
    ]
