# Generated by Django 6.0.6 on 2026-08-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0014_user_selected_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Close of the entry candle', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Close of the candle `horizon` bars after entry', max_digits=14, null=True),
        ),
    ]
