# Generated by Django 6.0.6 on 2026-10-04 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0017_tradingsignal_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro')], max_length=10)),
                ('amount_kes', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=12)),
                ('merchant_request_id', models.CharField(blank=True, default='', max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('result_code', models.CharField(blank=True, default='', max_length=20)),
                ('result_description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='trading_app.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='trading_app_user_id_7c63c3_idx'), models.Index(fields=['merchant_request_id'], name='trading_app_merchan_d4bbcb_idx')],
            },
        ),
    ]
