# Generated by Django 6.0.6 on 2026-10-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0019_secure_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ANALYSIS_FAILED', 'Analysis failed'), ('FEED_FAILED', 'Market data unavailable'), ('FEED_SUCCEEDED', 'Market data available')], max_length=32)),
                ('market', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
