# Generated by Django 6.0.6 on 2026-10-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0020_systemevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_bypass',
            field=models.BooleanField(default=False, help_text='Admin grant for bot access independent of subscription access'),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('previous_state', models.JSONField(default=dict)),
                ('new_state', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('affected_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
