# Generated by Django 6.0.6 on 2026-10-05 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0021_user_bot_bypass_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='evidence_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='granularity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='strategy_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AnalysisWaitCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('granularity', models.PositiveIntegerField()),
                ('wait_started_at', models.DateTimeField()),
                ('wait_expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_wait_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'symbol', 'granularity'), name='unique_analysis_wait_cycle')],
            },
        ),
    ]
