# Generated by Django 6.0.6 on 2026-10-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0022_tradingsignal_evidence_at_tradingsignal_granularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
